title: Get Infected!
content: |
  <div class="well">
    <a href="http://oatsea.org/contact/">Contact OATSEA</a> to join the alpha testing team!
  </div>
  
    <div class="jumbotron"><h1>Android</h1>
  <p><b>Step 1:</b> Download & Install Webserver - <a href="/infect/DroidPHP.apk" >DropidPHP</a></p>
  <p><a class="btn lrg btn-success" href="/infect/DroidPHP.apk" >Get DropidPHP</a></p>
  <p><b>Step 2:</b> Start the DroidPHP webserver app</p>
  
  <p><b>Step 3:</b> Download, Install and Open Teacher Virus - <a href="/infect/teachervirus.apk">Teacher Virus APK</a></p>
  <p><a class="btn lrg btn-success" href="/infect/teachervirus.apk">Get Android Teacher Virus</a></p>
  
  <p><b>Note:</b> You will need to authorise installation of non marketplace apps in your Android Settings</p>
  </div>
  
  ##Other Devices?
  
  **Step 1:** Download & Install Webserver of your choice. 
  
  **Step 2:** Download and unzip <a href="/infect/getinfected.php.zip">getinfected.php</a> to "root" of webserver public folder (e.g. htdocs, public_html or /var/www on raspberry Pi)
  
  **Step 3:** Open web browser and access that file on your webserver and follow install process.
