title: Get Infected!
content: |
  <div class="jumbotron"><h1>Android</h1>
  <p><b>Step 1:</b> Download & Install Webserver - <a href="/infect/DroidPHP.apk" >DropidPHP APK</a></p>
  <p><b>Step 1.5:</b>Download and unzip <a href="/infect/getinfected.php.zip">getinfected<a> and place in htdocs</p> 
  <p><b>Step 2:</b> Download & Install Teacher Virus - <a href="/infect/teachervirus.apk" >Teacher Virus APK</a></p>
  <p><b>Step 3:</b> Start the DroidPHP webserver and the Open Teacher Virus App and click on getinfected.php</p>
  </div>
  
  ##Other Devices?
  
  **Step 1:** Download & Install Webserver of your choice. 
  
  **Step 2:** Download and unzip <a href="/infect/getinfected.php.zip">getinfected.php</a> to "root" of webserver public folder (e.g. htdocs, public_html or /var/www on raspberry Pi)
  
  **Step 3:** Open web browser and access that file on your webserver and follow install process.
